#!/bin/bash
if [ -z "$1" ]
  then
    git commit -am 'refact: ' -e
  else
    if [ -z "$2" ]
      then
        git commit -am "refactor: $1"
      else
        git commit -am "refactor($1): $2"
    fi
fi
