#!/bin/bash
if [ -z "$1" ]
  then
    git commit -am 'refact: ' -e
  else
    if [ -z "$2" ]
      then
        git commit -am "refact: $1"
      else
        echo "refactor($1): $2"
        git commit -am "refact($1): $2"
    fi
fi
