#!/bin/bash
if [ -z "$1" ]
  then
    git commit -am 'test(*): ' -e
  else
    if [ -z "$2" ]
      then
        git commit -am "test(*): $1"
      else
        echo "test($1): $2"
        git commit -am "test($1): $2"
    fi
fi
